sudo: required
services:
  - docker

before_install:
  - docker build -t tolugeoge/docker-reaction -f Dockerfile.dev .

script:
  - docker run -e CI=true tolugeoge/docker-reaction npm run test


deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker"
  env: "Docker-env"
  bucker_name: "elasticbeanstalk-us-east-1-453592425056"
  bucker_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
  skip_cleanup: true
